FROM i3c/base/ubuntu18

RUN apt-get update && apt-get -y install zip unzip sudo curl \
    && cd /tmp \
    && wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip \
    && unzip terraform_0.11.13_linux_amd64.zip \
    && mv terraform /usr/local/bin/ 
#   && ln -sf /usr/local/bin/terraform /tf

#COPY env.sh /
COPY tf.sh /tf
RUN chmod a+x /tf
WORKDIR /i3c/data