FROM i3c/base/ubuntu18


RUN apt-get -y update && apt-get -y install ansible openssh-client sudo vim

COPY ans.sh /ans
COPY ans-play.sh /ans-play
COPY addHost.sh /addHost
RUN chmod a+x /ans && chmod a+x /ans-play && chmod a+x /addHost
RUN adduser ansible && adduser ansible sudo && cp -R /home /home.backup && echo "ansible  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ansible && chmod 0440 /etc/sudoers.d/ansible
USER ansible
 
WORKDIR /i3c/data